### PR TITLE
32 [WIP] minor edititem issues

### PR DESCRIPTION
**Pull request by jschirrmacher**
This solves #32 and #33

### CODE REVIEW

**Review by vbarzana — APPROVED** [review]

**Comment by vbarzana** [comment]
Hi Joachim I am not merging it yet because of the WIP title though, but the changes look good.

**Comment by jschirrmacher** [comment]
Thanks, @vbarzana, I made the WIP because not all parts of #32 and #33 are yet included. Whats currently missing:

- Once a shopping list is opened, it automatically switches to edit mode, which is painful if you just want to check what's on the list
- Clicking outside the item should trigger the save

Regarding the first, I wait for more information from @mrsimpson because I cannot reproduce this problem.

Also, I'd like to resize the 'quantity' field to be smaller, but didn't find a way to do so with the `IonInput`. I thought of using the `size="xs"` attribute, but it doesn't change anything. Maybe you have an idea?

**Comment by jschirrmacher** [comment]
I needed to change to WIP again, because after rebasing there are new problems regarding the new `getMyCurrentShoppingListItems` function... I need to check what's wrong with that.

**Comment by mrsimpson** [comment]
@jschirrmacher when re-implementing the "client side backend", I noticed that earlier, the items were an array in the shopping list document. I now changed this to be a sub collection. Actually, this should not have been an issue, but this may be a reason.

You may check the `Shopping.js`, it holds the updated code.
It may be that you need to create a new test list, I guess.

**Comment by jschirrmacher** [comment]
I think this happens because I don't have a Shopping list in the database. I never had one. It would need to be created if there is none. Should be part of the `Store`, but this should be solved outside of this branch IMO and then this branch should be rebased again before being merged.

**Comment by jschirrmacher** [comment]
See #39

**Pull request merged**
